var products = {
  newProduct: [
    {
      id: 1,
      img: "cauliflower.jpg",
      name: "Cauliflower China",
      species: "Green Vegetables",
      price: 100,
    },
    {
      id: 2,
      img: "gourd.jpg",
      name: "Gourd Golden Local",
      species: "Green vegetables",
      price: 80,
    },
    {
      id: 3,
      img: "eggplant.jpg",
      name: "Eggplant Korean – 1 Kg",
      species: "Cruciferous",
      old_price: 70,
      price: 65,
    },
    {
      id: 4,
      img: "mango.jpg",
      name: "Mango Blue Local",
      species: "Allium",
      price: 115,
    },
    {
      id: 5,
      img: "peas.jpg",
      name: "Bottol Gaurd (Lauki)",
      species: "Broad Beans",
      old_price: 85,
      price: 60,
    },
    {
      id: 6,
      img: "sapoche.jpg",
      name: "Broccoli Local",
      species: "Allium",
      price: 100,
    },
    {
      id: 7,
      img: "sweetCabbage.jpg",
      name: "Cabbage Band Gobhi",
      species: "Allium",
      price: 95,
    },
    {
      id: 8,
      img: "passion_fruit.jpg",
      name: "Passin Fruit Lao",
      species: "Allium",
      price: 10,
    },
    {
      id: 9,
      img: "lemon.jpg",
      name: "European Lemon Zest",
      species: "Allium",
      old_price: 80,
      price: 70,
    },
    {
      id: 10,
      img: "mustardGreens.jpg",
      name: "MustardGreens Local",
      species: "Green peas",
      price: 95,
    },
    {
      id: 11,
      img: "eggplant.jpg",
      name: "Eggplant Fruit Local",
      species: "Allium",
      price: 115,
    },
    {
      id: 12,
      img: "tomato.jpg",
      name: "Tomato Red Asian",
      species: "Allium",
      price: 78,
    },
  ],
  deals: [
    {
      id: 3,
      img: "gourd_big.jpg",
      name: "Apple Gourd – 1 Kg",
      species: "Cruciferous",
      old_price: 70,
      price: 65,
    },
    {
      id: 5,
      img: "peas_big.jpg",
      name: "Bottol Gaurd (Lauki)",
      species: "Broad Beans",
      old_price: 85,
      price: 60,
    },
    {
      id: 9,
      img: "lemon_big.jpg",
      name: "European Lemon Zest",
      species: "Allium",
      old_price: 80,
      price: 70,
    },
  ],
};

export default products;
